default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] || 'root' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'p@ssw0rd' %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  port: <%= ENV['DB_PORT'] || '5432' %>
  pool: <%= ENV['DB_POOL'] || '5' %>

development:
  <<: *default
  database: byte_store_dev

test:
  <<: *default
  database: byte_store_test

production:
  <<: *default
  database: byte_store_production
