default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: root
  password: p@ssw0rd
  pool: 5

development:
  <<: *default
  database: byte_store_dev

test:
  <<: *default
  database: byte_store_test

production:
  <<: *default
  database: byte_store_production
  username: riko_cusko
  password: <%= ENV["BYTE_STORE_DATABASE_PASSWORD"] %>
