name: Deploy to Render

on:
  push:
    branches:
      - 9_add_gems_and_automate_deployment  # Trigger deployment on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: myapp_test
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run Bundle Audit
      run: |
        gem install bundler-audit
        bundle audit check --update

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{"serviceId": "srv-cqb8lcaj1k6c73anvpd0", "branch": "master"}' \
          https://api.render.com/v1/services/srv-cqb8lcaj1k6c73anvpd0/deploys

    - name: Checkout clean repository
      uses: actions/checkout@v2
      with:
        clean: true

# service id can be obtained from your render dashboard url
